

spring.application.name=company-backend

spring.datasource.url=jdbc:postgresql://dpg-d6f7bnggjchc73fi5i0g-a:5432/companydb_7v4s?sslmode=require
spring.datasource.username=companydb_7v4s
spring.datasource.password=lB7ntaJMCC9UU8ZLlgDh8BKfgrQPvMzw

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.port=8080

# ===============================
# SERVER
# ===============================


# ===============================
# JWT
# ===============================
jwt.secret=codeo-soft-solutions-super-secure-jwt-secret-key-2026
jwt.expiration=86400000